### PR TITLE
OPAL-603 Acceptance Demo Fixes

### PR DESCRIPTION
**Pull request by AM-USAF**

### CODE REVIEW

**Review by JR-USAF — APPROVED** [review]
Looks good

**Review by JR-USAF — CHANGES_REQUESTED** [review]
Are there other places where you adjusted line lengths with strings that need changed?

**Comment by AM-USAF** [comment]
> 1. Are there other places where you adjusted line lengths with strings that need changed?
> 2. Are you planning on adding instructions on how to spin up argo/minikube to the README

1. Those were the only two places I did that; only the first instance was the one giving the error but I wanted to fix the second one just in case
2. Yes but not for this PR, it will be part of this branch later with a commit including a new file added to the resources tab to reduce the amount of work it takes to run it locally.

**Review by JR-USAF — APPROVED** [review]
Nice work!!!

**Review by MM-USAF — APPROVED** [review]
Tested this out with the help of Anna(@AM-USAF) everything is working as expected

**Pull request merged**
